from enum import StrEnum


class AIProvenanceStatus(StrEnum):
    CREATED = "CREATED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

    @property
    def is_terminal(self) -> bool:
        return self in {
            AIProvenanceStatus.SUCCEEDED,
            AIProvenanceStatus.REJECTED,
            AIProvenanceStatus.FAILED,
            AIProvenanceStatus.CANCELLED,
        }


class AIExecutionEventType(StrEnum):
    EXECUTION_CREATED = "EXECUTION_CREATED"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    PROTECTION_COMPLETED = "PROTECTION_COMPLETED"
    ROUTE_SELECTED = "ROUTE_SELECTED"
    PROVIDER_ATTEMPT_STARTED = "PROVIDER_ATTEMPT_STARTED"
    PROVIDER_ATTEMPT_SUCCEEDED = "PROVIDER_ATTEMPT_SUCCEEDED"
    PROVIDER_ATTEMPT_FAILED = "PROVIDER_ATTEMPT_FAILED"
    EXECUTION_SUCCEEDED = "EXECUTION_SUCCEEDED"
    EXECUTION_REJECTED = "EXECUTION_REJECTED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_CANCELLED = "EXECUTION_CANCELLED"


class AIExecutionStage(StrEnum):
    VALIDATION = "VALIDATION"
    POLICY = "POLICY"
    PROTECTION = "PROTECTION"
    ROUTING = "ROUTING"
    PROVIDER = "PROVIDER"
    OUTPUT_VALIDATION = "OUTPUT_VALIDATION"
    PROVENANCE = "PROVENANCE"
    INTERNAL = "INTERNAL"
    CANCELLATION = "CANCELLATION"


class AIProviderAttemptKind(StrEnum):
    PRIMARY = "PRIMARY"
    RETRY = "RETRY"
    FALLBACK = "FALLBACK"


class AIProviderAttemptStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class AICostBasis(StrEnum):
    PROVIDER_REPORTED = "PROVIDER_REPORTED"
    PRIVEXA_CALCULATED = "PRIVEXA_CALCULATED"
